// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pbadraH60A01.Models;

#nullable disable

namespace pbadraH60A01.Migrations
{
    [DbContext(typeof(H60assignmentDbPbadraContext))]
    [Migration("20241002220120_IdentitySetup")]
    partial class IdentitySetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pbadraH60A01.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            CartItemId = 1,
                            CartId = 1,
                            Price = 22000.00m,
                            ProductId = 9,
                            Quantity = 3
                        },
                        new
                        {
                            CartItemId = 2,
                            CartId = 1,
                            Price = 12000.00m,
                            ProductId = 17,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("pbadraH60A01.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CreditCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CreditCard = "4111 1111 1111 1111",
                            Email = "rchan@gmail.com",
                            FirstName = "Richard",
                            LastName = "Chan",
                            PhoneNumber = "8192346544",
                            Province = "ON"
                        },
                        new
                        {
                            CustomerId = 2,
                            CreditCard = "5500 0000 0000 0004",
                            Email = "emily.johnson@example.com",
                            FirstName = "Emily",
                            LastName = "Johnson",
                            PhoneNumber = "6134567890",
                            Province = "QC"
                        },
                        new
                        {
                            CustomerId = 3,
                            CreditCard = "3400 0000 0000 009",
                            Email = "michael.smith@example.com",
                            FirstName = "Michael",
                            LastName = "Smith",
                            PhoneNumber = "5147891234",
                            Province = "BC"
                        });
                });

            modelBuilder.Entity("pbadraH60A01.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFulfilled")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            DateCreated = new DateTime(2024, 10, 2, 22, 1, 19, 857, DateTimeKind.Utc).AddTicks(712),
                            DateFulfilled = new DateTime(2024, 10, 2, 22, 1, 19, 857, DateTimeKind.Utc).AddTicks(713),
                            Taxes = 13999.99m,
                            Total = 139999.97m
                        });
                });

            modelBuilder.Entity("pbadraH60A01.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderItemId = 1,
                            OrderId = 1,
                            Price = 75000.00m,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemId = 2,
                            OrderId = 1,
                            Price = 35000.00m,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemId = 3,
                            OrderId = 1,
                            Price = 26000.00m,
                            ProductId = 9,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("pbadraH60A01.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<decimal?>("BuyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProdCatId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SellPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("ProdCatId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            BuyPrice = 65000.00m,
                            Description = "Beneteau Oceanis 30.1",
                            Manufacturer = "Beneteau",
                            ProdCatId = 1,
                            SellPrice = 75000.00m,
                            Stock = 5
                        },
                        new
                        {
                            ProductId = 2,
                            BuyPrice = 45000.00m,
                            Description = "Catalina 320",
                            Manufacturer = "Catalina Yachts",
                            ProdCatId = 1,
                            SellPrice = 55000.00m,
                            Stock = 3
                        },
                        new
                        {
                            ProductId = 3,
                            BuyPrice = 120000.00m,
                            Description = "Jeanneau Sun Odyssey 410",
                            Manufacturer = "Jeanneau",
                            ProdCatId = 1,
                            SellPrice = 140000.00m,
                            Stock = 4
                        },
                        new
                        {
                            ProductId = 4,
                            BuyPrice = 35000.00m,
                            Description = "Hunter 33",
                            Manufacturer = "Hunter Marine",
                            ProdCatId = 1,
                            SellPrice = 45000.00m,
                            Stock = 2
                        },
                        new
                        {
                            ProductId = 5,
                            BuyPrice = 30000.00m,
                            Description = "Sea Ray SPX 190",
                            Manufacturer = "Sea Ray",
                            ProdCatId = 2,
                            SellPrice = 35000.00m,
                            Stock = 7
                        },
                        new
                        {
                            ProductId = 6,
                            BuyPrice = 55000.00m,
                            Description = "Chaparral 23 SSi",
                            Manufacturer = "Chaparral Boats",
                            ProdCatId = 2,
                            SellPrice = 60000.00m,
                            Stock = 5
                        },
                        new
                        {
                            ProductId = 7,
                            BuyPrice = 25000.00m,
                            Description = "Bayliner VR5",
                            Manufacturer = "Bayliner",
                            ProdCatId = 2,
                            SellPrice = 30000.00m,
                            Stock = 8
                        },
                        new
                        {
                            ProductId = 8,
                            BuyPrice = 75000.00m,
                            Description = "Cobalt R30",
                            Manufacturer = "Cobalt Boats",
                            ProdCatId = 2,
                            SellPrice = 85000.00m,
                            Stock = 3
                        },
                        new
                        {
                            ProductId = 9,
                            BuyPrice = 22000.00m,
                            Description = "Lund 1775 Crossover XS",
                            Manufacturer = "Lund Boats",
                            ProdCatId = 3,
                            SellPrice = 26000.00m,
                            Stock = 10
                        },
                        new
                        {
                            ProductId = 10,
                            BuyPrice = 26000.00m,
                            Description = "Tracker Pro Guide V-175 Combo",
                            Manufacturer = "Tracker Boats",
                            ProdCatId = 3,
                            SellPrice = 30000.00m,
                            Stock = 6
                        },
                        new
                        {
                            ProductId = 11,
                            BuyPrice = 35000.00m,
                            Description = "Ranger Z518",
                            Manufacturer = "Ranger Boats",
                            ProdCatId = 3,
                            SellPrice = 40000.00m,
                            Stock = 4
                        },
                        new
                        {
                            ProductId = 12,
                            BuyPrice = 45000.00m,
                            Description = "Bass Cat Cougar FTD",
                            Manufacturer = "Bass Cat Boats",
                            ProdCatId = 3,
                            SellPrice = 50000.00m,
                            Stock = 2
                        },
                        new
                        {
                            ProductId = 13,
                            BuyPrice = 800000.00m,
                            Description = "Sunseeker Predator 55",
                            Manufacturer = "Sunseeker",
                            ProdCatId = 4,
                            SellPrice = 950000.00m,
                            Stock = 1
                        },
                        new
                        {
                            ProductId = 14,
                            BuyPrice = 950000.00m,
                            Description = "Princess V60",
                            Manufacturer = "Princess Yachts",
                            ProdCatId = 4,
                            SellPrice = 1150000.00m,
                            Stock = 1
                        },
                        new
                        {
                            ProductId = 15,
                            BuyPrice = 600000.00m,
                            Description = "Fairline Targa 45",
                            Manufacturer = "Fairline",
                            ProdCatId = 4,
                            SellPrice = 700000.00m,
                            Stock = 2
                        },
                        new
                        {
                            ProductId = 16,
                            BuyPrice = 1400000.00m,
                            Description = "Azimut S6",
                            Manufacturer = "Azimut",
                            ProdCatId = 4,
                            SellPrice = 1600000.00m,
                            Stock = 1
                        },
                        new
                        {
                            ProductId = 17,
                            BuyPrice = 12000.00m,
                            Description = "Sea-Doo GTX 170",
                            Manufacturer = "Sea-Doo",
                            ProdCatId = 5,
                            SellPrice = 15000.00m,
                            Stock = 10
                        },
                        new
                        {
                            ProductId = 18,
                            BuyPrice = 8000.00m,
                            Description = "Yamaha EX Deluxe",
                            Manufacturer = "Yamaha",
                            ProdCatId = 5,
                            SellPrice = 10000.00m,
                            Stock = 8
                        },
                        new
                        {
                            ProductId = 19,
                            BuyPrice = 15000.00m,
                            Description = "Kawasaki Jet Ski Ultra 310R",
                            Manufacturer = "Kawasaki",
                            ProdCatId = 5,
                            SellPrice = 18000.00m,
                            Stock = 5
                        },
                        new
                        {
                            ProductId = 20,
                            BuyPrice = 14000.00m,
                            Description = "Sea-Doo RXT-X 300",
                            Manufacturer = "Sea-Doo",
                            ProdCatId = 5,
                            SellPrice = 17000.00m,
                            Stock = 7
                        });
                });

            modelBuilder.Entity("pbadraH60A01.Models.ProductCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("ProdCat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ProdCat = "Sailboats"
                        },
                        new
                        {
                            CategoryId = 2,
                            ProdCat = "Motorboats"
                        },
                        new
                        {
                            CategoryId = 3,
                            ProdCat = "Fishing Boats"
                        },
                        new
                        {
                            CategoryId = 4,
                            ProdCat = "Yachts"
                        },
                        new
                        {
                            CategoryId = 5,
                            ProdCat = "Jet Skis"
                        });
                });

            modelBuilder.Entity("pbadraH60A01.Models.ShoppingCart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("ShoppingCarts");

                    b.HasData(
                        new
                        {
                            CartId = 1,
                            CustomerId = 2,
                            DateCreated = new DateTime(2024, 10, 2, 22, 1, 19, 857, DateTimeKind.Utc).AddTicks(667)
                        });
                });

            modelBuilder.Entity("pbadraH60A01.Models.CartItem", b =>
                {
                    b.HasOne("pbadraH60A01.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pbadraH60A01.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("pbadraH60A01.Models.Order", b =>
                {
                    b.HasOne("pbadraH60A01.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("pbadraH60A01.Models.OrderItem", b =>
                {
                    b.HasOne("pbadraH60A01.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pbadraH60A01.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("pbadraH60A01.Models.Product", b =>
                {
                    b.HasOne("pbadraH60A01.Models.ProductCategory", "ProdCat")
                        .WithMany("Products")
                        .HasForeignKey("ProdCatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdCat");
                });

            modelBuilder.Entity("pbadraH60A01.Models.ShoppingCart", b =>
                {
                    b.HasOne("pbadraH60A01.Models.Customer", "Customer")
                        .WithOne("ShoppingCart")
                        .HasForeignKey("pbadraH60A01.Models.ShoppingCart", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("pbadraH60A01.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("pbadraH60A01.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("pbadraH60A01.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("pbadraH60A01.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("pbadraH60A01.Models.ShoppingCart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
